SELECT MAJOR, ROUND(AVG(AVR),2) 
FROM STUDENT 
GROUP by major HAVING MAJOR != '화학';

SELECT MAJOR, ROUND(AVG(AVR),2) 
FROM STUDENT
WHERE MAJOR != '화학'
GROUP by major HAVING AVG(AVR)< 2;

-----------------------------------------------------

SELECT p.PNO, PNAME, CNO, CNAME
FROM PROFESSOR p, COURSE c
WHERE P.PNO = c.PNO AND PNAME = '송강';

SELECT PNO, PNAME, CNO, CNAME
FROM COURSE
JOIN PROFESSOR USING(pno)
WHERE PNAME = '송강';

SELECT p.PNO, PNAME, CNO, CNAME
FROM PROFESSOR p, COURSE c
WHERE P.PNO = c.PNO AND CNAME like '%화학%';

SELECT PNO, PNAME, CNO, CNAME
FROM COURSE
JOIN PROFESSOR USING(pno)
WHERE CNAME like '%화학%';

SELECT * FROM STUDENT;
SELECT * FROM SCORE;
SELECT * FROM COURSE;

SELECT PNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
FROM STUDENT
join SCORE USING(SNO)
join COURSE USING(CNO)
WHERE SYEAR = 1 AND MAJOR = '화학';

